name: generate-rules

on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # check it to your workflow can access it
      # from: https://github.com/actions/checkout
      - name: Checkout repo
        uses: actions/checkout@master
      
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE }}

      # from: https://github.com/actions/setup-node
      - name: Setup node
        uses: actions/setup-node@master
        with:
          node-version: 20

      - uses: pnpm/action-setup@v3
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      # - name: init Sub-Store Env
      #   run: |
      #     # wget  -P ./subStore/ -N https://github.com/sub-store-org/Sub-Store/releases/latest/download/sub-store.min.js
      
      - name: Generate rules
        run: |
          export TZ='Asia/Shanghai'
          # nohup node ./subStore/sub-store.min.js > sub-store.log 2>&1 &
          node ./subStore/sub-store.min.js
          ls 
          cat sub-store.log
          node ./scripts/init-substore.js
          npm run generate
          npm run no-empty-line
          npm run upload
        env:
          SURGIO_URL_BASE: ${{ secrets.SURGIO_URL_BASE }}
          SURGIO_UPLOAD_REGION: ${{ secrets.SURGIO_UPLOAD_REGION }}
          SURGIP_UPLOAD_PREFIX: ${{ secrets.SURGIP_UPLOAD_PREFIX }}
          SURGIP_UPLOAD_BUCKET: ${{ secrets.SURGIP_UPLOAD_BUCKET }}
          SURGIP_UPLOAD_ACCESS_KEY_ID: ${{ secrets.SURGIP_UPLOAD_ACCESS_KEY_ID }}
          SURGIP_UPLOAD_ACCESS_KEY_SECRET: ${{ secrets.SURGIP_UPLOAD_ACCESS_KEY_SECRET }}
          PRIVATE_GIST_ID: ${{ secrets.PRIVATE_GIST_ID }}
          PRIVATE_GIST_ID_COMPANY: ${{ secrets.PRIVATE_GIST_ID_COMPANY }}
          MITM_CA_PASSPHRASE: ${{ secrets.MITM_CA_PASSPHRASE }}
          MITM_CA_P12: ${{ secrets.MITM_CA_P12 }}
          CF_WIREGUARD_PUBLICK_KEY: ${{ secrets.CF_WIREGUARD_PUBLICK_KEY }}
          CF_WIREGUARD_PRIVATE_KEY: ${{ secrets.CF_WIREGUARD_PRIVATE_KEY }}
          SUBSTORE_GIT_USER: ${{ secrets.SUBSTORE_GIT_USER }}
          SUBSTORE_GIST_TOKEN: ${{ secrets.SUBSTORE_GIST_TOKEN }}
          SUBSTORE_API_URL: ${{ secrets.SUBSTORE_API_URL }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          deploy_key: ${{ secrets.SSH_PRIVATE }}
          external_repository: ProxyStorage/rule_generate
          publish_branch: gh-pages
          publish_dir: dist

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          retain_days: 0
          keep_minimum_runs: 0
